changelog:
  categories:
    - title: Dependencies
      labels:
        - "Type: Dependency"
    - title: matching-service
      labels:
        - "Component: Matching"
    - title: dispatch-service
      labels:
        - "Component: Dispatch"
    - title: handler-core
      labels:
        - "Component: Handler-Core"
    - title: dms-service
      labels:
        - "Component: DMS"
    - title: invoice-service
      labels:
        - "Component: Invoice"
