# For documentation see https://jboss-container-images.github.io/openjdk/
FROM registry.access.redhat.com/ubi9/openjdk-21-runtime

# Copy runnable jar to deployments
COPY target/dms-service-*.jar /deployments/application.jar