name: release

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module to release'
        type: choice
        required: true
        options:
          - matching-service
          - dispatch-service
          - handler-core
          - dms-service
      release-version:
        description: 'Release version'
        type: string
        required: true
        default: "X.Y.Z"
      next-version:
        description: "Next version to use after release"
        type: string
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      # requires checkout for local action
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Maven build and release
        uses: ./.github/actions/release-maven
        with:
          module: ${{ inputs.module }}
          release-version: ${{ inputs.release-version }}
          next-version: ${{ inputs.next-version }}
          gpg-private-key: ${{ secrets.gpg_private_key }}
          gpg-passphrase: ${{ secrets.gpg_passphrase }}
          sonatype-username: ${{ secrets.sonatype_username }}
          sonatype-password: ${{ secrets.sonatype_password }}

  build-image:
    if: ${{ inputs.module != 'handler-core' }}
    needs: build-maven
    runs-on: ubuntu-latest
    steps:
      - name: Build and push image
        uses: it-at-m/.github/.github/actions/action-build-image@main
        with:
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          path: "./${{ inputs.module }}"
          artifact-name: "target"
          image-name: ${{ inputs.module }}
          image-tags: |
            type=raw,value=${{ inputs.release-version }}
            type=raw,value=latest

  create-github-release:
    if: ${{ !failure() && !cancelled() }}
    needs: "build-image"
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: "${{ inputs.module }}_${{ github.event.inputs.release-version }}"
          draft: false
          prerelease: false
          generate_release_notes: true
